version: '3.1'

volumes:
  pg_selectel:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    volumes:
      - ./init-db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '127.0.0.1:5438:5432'
  go-docker-image:
    build: ./
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    links:
      - "pg_db:database"